### ISSUE TITLE
Install VIAME-Web on new machine 

### ISSUE THREAD

**Issue by aashish24** [VIAME/VIAME-Web#501]

**Comment by subdavis** [comment]
What are you thinking for customizing the branding in the client?

## Options

1. Build-time configuration: use environment variables and build a new image based on 
2. Run-time configuration.  Make this more of a traditional deployable service and just use some settings in girder / json item / something to point to a logo, title, and other such.  

Run-time definitely makes the secondary server easier to deploy: we can just use the image from docker hub.  The login message is a little complicated though.

**Comment by subdavis** [comment]
#  Tasks

- [x] insstall on new machine
- [ ] SSL and external domain setup (maybe try traefik?) [BLOCKED]
- [ ] Get a list of videos and annotations to populate [BLOCKED]
- [ ] Rebranding work

**Comment by subdavis** [comment]
Not going to block on the other issues.

#532 will be merged, but is already deployed on test server.
